from abaqusConstants import *

nodes = []
edges = []

nodes_fname = './Nodes.txt'
with open(nodes_fname) as fp:
    line = fp.readline()
    count = 0
    while line:
        xy = line.split(' ')
        xy = (float(xy[0]), float(xy[1]), float(xy[2].rstrip('\n')))
        nodes.append(xy)
        line = fp.readline()

edges_fname = './Edges.txt'
with open(edges_fname) as fp:
    line = fp.readline()
    count = 0
    while line:
        xy = line.split(' ')
        xy = (int(xy[0]), int(xy[1].rstrip('\n')))
        edges.append(xy)
        line = fp.readline()


for i in edges:
    print(i)
p = mdb.models['Model-1'].Part(name='Geodesic_Dome', dimensionality=THREE_D, type=DEFORMABLE_BODY)

# Paste the list of nodes generated by DomeGenerator.py here

for j in range(len(nodes)):
    dtm = p.DatumPointByCoordinate(coords=nodes[j])

# Paste the list of nodes generated by DomeGeneitgirator.py here

d = p.datums
for i in edges:
    p.WirePolyLine(points=(d[i[0]], d[i[1]]), mergeType=IMPRINT)
